# -*- coding: utf-8 -*-
"""Sign_Language.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oA4MgwPi6Hkanzi5aB0smKE7wcuDZ-bQ
"""

from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D, Flatten, Dense
from keras.preprocessing.image import ImageDataGenerator
model = Sequential()

model.add(Convolution2D(16, (2,2), input_shape=(64, 64, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Convolution2D(32, (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(3, 3)))
model.add(Convolution2D(64, (5,5), activation='relu'))
model.add(MaxPooling2D(pool_size=(5, 5)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(28, activation='softmax'))

model.summary()

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

"""from google.colab import drive
drive.mount('/content/drive')
"""

import os

data_dir = '/content/drive/MyDrive/Sign/Sign_Language'

import zipfile

with zipfile.ZipFile(data_dir + '.zip', 'r') as zip_ref:
    zip_ref.extractall('/tmp/image_dataset')

data_dir = '/tmp/image_dataset/Sign_Language'

train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        data_dir+'/asl_alphabet_train/',
        target_size=(64, 64),
        batch_size=32,
        class_mode='categorical')

validation_generator = test_datagen.flow_from_directory(
        data_dir+'/asl_alphabet_test/',
        target_size=(64, 64),
        batch_size=32,
        class_mode='categorical')

model.fit(
        train_generator,
        epochs=8,
        validation_data=validation_generator,
        )

model.save('sl.h5')

model_save_name = 'sl.h5'
path = F"/content/drive/MyDrive/Sign/{model_save_name}"
torch.save(model.state_dict(), path)

from keras.models import load_model
import keras.utils as image
m=load_model('sl.h5')

# example of loading an image with the Keras API
from tensorflow.keras.utils import load_img
test_image=load_img('/content/drive/MyDrive/Sign/a.jpeg', target_size=(64, 64))

type(test_image)
test_image

import numpy as np
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image, axis=0)
test_image.shape

test_image.ndim

model.predict(test_image)

train_generator.class_indices

